/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TourRouteRouteImport } from "./routes/tour/route"
import { Route as SettingsRouteRouteImport } from "./routes/settings/route"
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route"
import { Route as BreakRouteRouteImport } from "./routes/break/route"
import { Route as R404RouteRouteImport } from "./routes/404/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthLoginRouteRouteImport } from "./routes/auth/login/route"
import { Route as AuthErrorRouteRouteImport } from "./routes/auth/error/route"
import { Route as AuthCallbackRouteRouteImport } from "./routes/auth/callback/route"

const TourRouteRoute = TourRouteRouteImport.update({
  id: "/tour",
  path: "/tour",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const BreakRouteRoute = BreakRouteRouteImport.update({
  id: "/break",
  path: "/break",
  getParentRoute: () => rootRouteImport,
} as any)
const R404RouteRoute = R404RouteRouteImport.update({
  id: "/404",
  path: "/404",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRouteRoute = AuthErrorRouteRouteImport.update({
  id: "/auth/error",
  path: "/auth/error",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRouteRoute = AuthCallbackRouteRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/404": typeof R404RouteRoute
  "/break": typeof BreakRouteRoute
  "/dashboard": typeof DashboardRouteRoute
  "/settings": typeof SettingsRouteRoute
  "/tour": typeof TourRouteRoute
  "/auth/callback": typeof AuthCallbackRouteRoute
  "/auth/error": typeof AuthErrorRouteRoute
  "/auth/login": typeof AuthLoginRouteRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/404": typeof R404RouteRoute
  "/break": typeof BreakRouteRoute
  "/dashboard": typeof DashboardRouteRoute
  "/settings": typeof SettingsRouteRoute
  "/tour": typeof TourRouteRoute
  "/auth/callback": typeof AuthCallbackRouteRoute
  "/auth/error": typeof AuthErrorRouteRoute
  "/auth/login": typeof AuthLoginRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/404": typeof R404RouteRoute
  "/break": typeof BreakRouteRoute
  "/dashboard": typeof DashboardRouteRoute
  "/settings": typeof SettingsRouteRoute
  "/tour": typeof TourRouteRoute
  "/auth/callback": typeof AuthCallbackRouteRoute
  "/auth/error": typeof AuthErrorRouteRoute
  "/auth/login": typeof AuthLoginRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/404"
    | "/break"
    | "/dashboard"
    | "/settings"
    | "/tour"
    | "/auth/callback"
    | "/auth/error"
    | "/auth/login"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/404"
    | "/break"
    | "/dashboard"
    | "/settings"
    | "/tour"
    | "/auth/callback"
    | "/auth/error"
    | "/auth/login"
  id:
    | "__root__"
    | "/"
    | "/404"
    | "/break"
    | "/dashboard"
    | "/settings"
    | "/tour"
    | "/auth/callback"
    | "/auth/error"
    | "/auth/login"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404RouteRoute: typeof R404RouteRoute
  BreakRouteRoute: typeof BreakRouteRoute
  DashboardRouteRoute: typeof DashboardRouteRoute
  SettingsRouteRoute: typeof SettingsRouteRoute
  TourRouteRoute: typeof TourRouteRoute
  AuthCallbackRouteRoute: typeof AuthCallbackRouteRoute
  AuthErrorRouteRoute: typeof AuthErrorRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tour": {
      id: "/tour"
      path: "/tour"
      fullPath: "/tour"
      preLoaderRoute: typeof TourRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/break": {
      id: "/break"
      path: "/break"
      fullPath: "/break"
      preLoaderRoute: typeof BreakRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/404": {
      id: "/404"
      path: "/404"
      fullPath: "/404"
      preLoaderRoute: typeof R404RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/login": {
      id: "/auth/login"
      path: "/auth/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/error": {
      id: "/auth/error"
      path: "/auth/error"
      fullPath: "/auth/error"
      preLoaderRoute: typeof AuthErrorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/callback": {
      id: "/auth/callback"
      path: "/auth/callback"
      fullPath: "/auth/callback"
      preLoaderRoute: typeof AuthCallbackRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404RouteRoute: R404RouteRoute,
  BreakRouteRoute: BreakRouteRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  TourRouteRoute: TourRouteRoute,
  AuthCallbackRouteRoute: AuthCallbackRouteRoute,
  AuthErrorRouteRoute: AuthErrorRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
